// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WeaponTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ranged);
	// Melee
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chainsaw);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalSword);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DemolitionGear);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShockBat);

	// Ranged
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comet);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalBurstRifle);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalGatling);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalHomingHighSpeed4);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalHomingLauncher4);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalLauncher2);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fireball);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HomingFireball);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IceShotgun);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThunderStrike);
}
